# IMPORT : IMPORTAR OBJETOS
# EX: IMPORT = BEBIDAS

# FROM : ALGUNS OBJETOS DESEJADOS.
# EX:FROM BEBIDA IMPORT

# BIBLIOTECA (MATH),
# SÉRIE DE FUNCIONALIDADES EXTRAS DE MATEMÁTICA.
# CEIL - ARREDONDAMENTO PRA CIMA
# FLOOR - ARREDONDAMENTO PRA BAIXO
# TRUNC - ELIMINAR A PARTE INTEIRA DO NUMERO .
# POW - POTENCIA
# SQRT - CALCULO DE RAIZ QUADRADA
# FACTORIAL -